### PR TITLE
Enable error handlers back

### PR DESCRIPTION
**Pull request by Jean85**
While discussing with a colleague, he made me notice that the current setup of the bundle doesn't report everything. Due to the disabled error handler, all `trigger_error` are ignored if they do not raise an exception; so deprecations or notices cannot be collected like this. This was also reported as with #318 by @ruudk.

With this PR I'm adding new, improved E2E tests to try and get back the handles, so we can collect all errors, without the old issue of duplicated events (see #156 as an example).

Please, test this out because I'm not 100% sure that my E2E tests are reproducing the real behavior correctly.

### CODE REVIEW

**Comment by ste93cry** [comment]
My fear is that by having two error handlers they could conflict or the errors could be handled twice or handled differently from what would happen without Sentry. What about investigating whether it's possible to attach to the Symfony error handler instead?

**Comment by Jean85** [comment]
The new end to end tests should keep us safe in regards of double reporting, and in fact I've spotted just one case, fatals, and I've safely ignored them.

As for attach points, there are only two and those are not sufficient: a PSR-3 logger and the possibility to attach an exception handler, nothing more.

**Comment by ste93cry** [comment]
Why it's the PSR-3 logger not sufficient?

**Comment by Jean85** [comment]
Because it's very limited in information, only level & message; no stack trace, for example.

**Comment by ste93cry** [comment]
To me it looks like the exception [is passed](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/ErrorHandler/ErrorHandler.php#L576) in the context 🤔 Did you look at how Monolog logs errors in a Symfony application?

**Comment by Jean85** [comment]
Monolog handler is a completely separate option in this bundle: #247

**Comment by ste93cry** [comment]
Sure, what I meant was to look at how Monolog was integrated in Symfony out-of-the-box (e.g. when it logs to `var/logs/*`) to understand if they use a custom error handler or not

**Comment by Jean85** [comment]
Monolog is PSR-3 compliant, so that interface is surely used as a junction. I can't do that without losing information, as I said.

Also, it seems that Symfony simply injects the `logger` service wherever is needed:
 * https://github.com/symfony/http-kernel/blob/a3b12e2925bc9f042b92e1ead400aab9ad408c76/EventListener/ErrorListener.php#L39
 * https://github.com/symfony/http-kernel/blob/a3b12e2925bc9f042b92e1ead400aab9ad408c76/EventListener/RouterListener.php#L72
 * https://github.com/symfony/http-kernel/blob/a3b12e2925bc9f042b92e1ead400aab9ad408c76/EventListener/DebugHandlersListener.php#L54

**Comment by ste93cry** [comment]
>I can't do that without losing information, as I said

We discussed this privately, but I'm gonna leave here some notes for future reference: as far as I remember from our conversation, you have at disposal everything you need from the Monolog context (the exception is always present under the `context.exception` field, and if it isn't present then the client will use the backtrace instead. Also, what I was talking about was to create a little PSR-3 implementation [to attach](https://github.com/symfony/symfony/blob/b2f210f1f3fb03533573a343d3f67e3c0b2225c1/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php#L79) to the Symfony ErrorHandler component. The issue however is that there can be only one logger at once registered with the handler, so we cannot go on with this proposal.

Said this, I see a big issue with this change, if I'm not missing something: it looks to me that now all integrations are enabled by default regardless of whether Monolog is used, so either you have to update the README to explain that you manually need to disable the `(FatalError|Error|Exception)ListenerIntegration` integrations or you need to  handle this case while configuring the DI container

**Comment by Jean85** [comment]
> Said this, I see a big issue with this change, if I'm not missing something: it looks to me that now all integrations are enabled by default regardless of whether Monolog is used, so either you have to update the README to explain that you manually need to disable the (FatalError|Error|Exception)ListenerIntegration integrations or you need to handle this case while configuring the DI container

Nope, that's not the case. The monolog-sentry integration is NOT enabled by default, as before; and there's already an option to shut off the listeners, useful if you enable the Monolog integration.

**Comment by ste93cry** [comment]
I know that the Monolog integration is enabled by default, but as soon as I enable it then those integrations should be disabled without having to do it manually, do you agree? The listener will also be disabled, but this does not prevent the error handler from being registered as soon as one of those integrations run, so it's better if they don't even get set up

**Comment by Jean85** [comment]
So you would bind the enabling of the default integrations to the `register_error_listener` option? That seems feasibile... I'll dig into it.

**Comment by ste93cry** [comment]
>So you would bind the enabling of the default integrations to the register_error_listener option

Yes, also because not doing this means breaking the compatibility with the current applications that have Monolog enabled: they will suddendly start having one new error handler registered, which could cause issues in the long run

**Comment by Jean85** [comment]
@ste93cry can I get an approval here? I would like to merge this and use it as a fallback after I implement integrating with Monolog as the first choice as you and [Nicolas suggested](https://github.com/symfony/symfony/issues/36472#issuecomment-616210651).

**Comment by Jean85** [comment]
Due to #337 + 02e6902, master is now 4.x. Fixing conflicts and merging now.

**Pull request merged**
