### PR TITLE
[BUGFIX] fixes the configuration tree

### PR DESCRIPTION
**Pull request by michaelzangerle**
Fixes issues discovered and discussed in issue https://github.com/getsentry/sentry-symfony/issues/41.

### CODE REVIEW

**Comment by michaelzangerle** [comment]
@Jean85 The failing tests are the same as in the master branch.

**Comment by Jean85** [comment]
Hi @michaelzangerle, thanks a lot for this contibution!

Master branch [is green](https://travis-ci.org/getsentry/sentry-symfony/builds/258193235), to what failures are you referring to?

Also, I would prefer to not remove the deprecated option from the readme. Can you add a paragraph called "Deprecated options" that just summarizes with a YAML snippet the deprecated structure of option?

Thanks!

**Comment by michaelzangerle** [comment]
@Jean85 Whoops it redirected me to the current build instead of the master build that's why I thought it also failed on master. But still do you have any idea why it's failing? It's not even in this bundle ... 

```
PHP Fatal error:  Class 'Raven_Processor_SanitizeDataProcessor' not found in /home/travis/build/getsentry/sentry-symfony/vendor/sentry/sentry/lib/Raven/Client.php on line 286
```

Yes I can add the deprecated options to the readme but is there any value to it? They should not be used anyway ...

**Comment by Jean85** [comment]
I've restarted the latest build on master and it's still green. You should issue a `composer update --prefer-lowest` to try and reproduce the issue in your local environment.

As for the deprecated options in the README, I would like to write about that to leave a notice about the deprecation itself, something like this:

> ## Deprecated options
> In previous releases of this bundle, some of the previous options where set outside of the `options` level of the configuration file. Those still work but are deprecated, and they will be dropped in the 2.x release, so **you are advised to abandon them**; to provide forward compatibility, they can be used alongside the standard syntax, but values must match. This is a list of those option:
> ```
> sentry:
>     deprecated-option1: ~
>     deprecated-option2: ~
>     deprecated-option3: ~
>     ...
> ```

**Comment by michaelzangerle** [comment]
@Jean85 Done and tests pass now.

**Pull request merged**
