### PR TITLE
fix: Make getTraceMeta() function public.

### PR DESCRIPTION
**Pull request by jbroutier**
Fixes https://github.com/getsentry/sentry-symfony/issues/627

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
On hold until #627 is sorted out.

**Review by Jean85 — CHANGES_REQUESTED** [review]
Fix is fine, can you add a changelog entry?

**Comment by ste93cry** [comment]
Are we really sure that this is not a bug in Twig itself? I mean, it worked fine until now, and suddenly a minor version is released and it breaks everything: it's weird...

**Comment by Jean85** [comment]
It seems related to https://github.com/twigphp/Twig/pull/3702
They changed the way in which they invoke callables, and ours was a private method...

We can try to report it as it is to see if they want to fix it or not.

**Review by Jean85 — CHANGES_REQUESTED** [review]
Stof suggested to us to switch to the more direct `public` method way (so with `[$this, 'methodName]`) since it would be more performant under Twig: https://github.com/twigphp/Twig/issues/3703#issuecomment-1127654569

**Comment by jbroutier** [comment]
PR updated with the direct method call. Do In need to rebase?

**Pull request merged**
