### PR TITLE
Exception listener with dedicated data methods

### PR DESCRIPTION
**Pull request by bouland**
Sorry for my PR #176, i used version 2.0.2 and didn't take last changes.

Issue #175

### CODE REVIEW

**Comment by Jean85** [comment]
I'm sorry but I think I've missed those too... Where did you got those changes? They aren't from this bundle, it seems. Maybe from a fork?

**Comment by bouland** [comment]
> I'm sorry but I think I've missed those too... Where did you got those changes? They aren't from this bundle, it seems. Maybe from a fork?

No fork, just folowing PR 
- [PR 167](https://github.com/getsentry/sentry-symfony/pull/167/files#diff-cdf99235fbbeccfa12764a4be188ae32R114)
- [PR 139](https://github.com/getsentry/sentry-symfony/pull/131/files#diff-cdf99235fbbeccfa12764a4be188ae32R189)

**Comment by bouland** [comment]
My goal is to write this overriding code
```php
class SentryExceptionListener extends ExceptionListener
{
    /**
     * @param object|string|UserInterface|SentryUserInterface $user
     */
    protected function setUserValue($user)
    {
        if (!$user instanceof SentryUserInterface) {
            parent::setUserValue($user);
            return;
        }

        $this->client->set_user_data(
            $user->getId(),
            $user->getEmail(),
            parent::getUserData() + $user->getSentryData()
        );
    }
}
```

**Comment by bouland** [comment]
UP !

What do you think about it ?

**Comment by Jean85** [comment]
Those are breaking changes for anyone that is extending the listener like you, so I cannot merge this as is.

**Pull request merged**
