### PR TITLE
Messenger: capture_soft_fails:false doesn't work

### PR DESCRIPTION
**Pull request by Jean85**
This stems from https://github.com/getsentry/sentry-symfony/pull/326#issuecomment-653455458: I've noticed that the `capture_soft_fails` option is not working for me, because the `willRetry` flag is set later, in a different listener with a priority of 100, where our listener has a default priority of 128.

### CODE REVIEW

**Comment by Jean85** [comment]
Ok, the bug seems to be absent on 4.3: https://travis-ci.org/github/getsentry/sentry-symfony/jobs/704627016

**Comment by Jean85** [comment]
@emarref this is ready, can you test it out?

**Comment by Jean85** [comment]
I personally tested this in production, it works.

**Comment by emarref** [comment]
Sorry about that. I've been under the gun with a deadline. It looks like it should work well. I'm still not sure why it was working OK for me in the first place.

**Pull request merged**
