### PR TITLE
Update RequestListener.php

### LINKED ISSUE #263: Undefined variable in RequestListener
Line 77 in RequestListener throws a notice when the if-statement above is false:
`Notice: Undefined variable: userData`

### PR DESCRIPTION
**Pull request by cklm**
fixes #263 and #264

### CODE REVIEW

**Comment by cklm** [comment]
Added entries in changelog - we are still using the `AuthorizationChecker` to check, if user-handling is activated. Seems not to be an error for me.

**Comment by Jean85** [comment]
Are you sure? We already have this check on the TokenStorage for that:

https://github.com/getsentry/sentry-symfony/blob/0a71ea681854bbe419bd14953ba8a7aa54d53dc2/src/EventListener/RequestListener.php#L63-L65

**Comment by cklm** [comment]
> Are you sure? We already have this check on the TokenStorage for that:
> 

you are right - thats a double-check - removed it

**Comment by cklm** [comment]
@Jean85 can you have a look here?

**Pull request merged**
