### PR TITLE
Remove monolog dependency

### PR DESCRIPTION
**Pull request by Melfo01**
Monolog repository is not used directly by this repository; so we can remove it ;)

### CODE REVIEW

**Comment by Melfo01** [comment]
Hey @cleptric 👋,

My tests fail with Symfony 6.0. I think the problem is caused by `symfony/psr-http-message-bridge` package. In master, tests was launched with version 2.3.1, my PR used 6.4 version. 

Do you know why and how to fix it?
Same question with PHPStan?

**Review by Jean85 — APPROVED** [review]

**Comment by ste93cry** [comment]
I have nothing against merging these changes, but I fail to understand how it could help with your problem as `monolog/monolog` is a development requirement and does not affect at all third parties.

**Comment by Jean85** [comment]
Well, at the very least we're testing that it works fine with that major.

**Comment by ste93cry** [comment]
Technically speaking, we don't even depend on `monolog/monolog` in this bundle, but rather on `symfony/monolog-bundle`, which is needed only for the E2E tests anyway. We could even remove the requirement on the lib imho, I don't see why it would be useful to keep it.

**Comment by ste93cry** [comment]
Yes please, that would be cool!

**Review by ste93cry — APPROVED** [review]

**Pull request merged**
