### PR TITLE
Releasing scope constraint

### PR DESCRIPTION
**Pull request by bouland**
Issue #175

### CODE REVIEW

**Comment by bouland** [comment]
Your welcome 😁
Do you have plan the next release soin ?
Or should i move to dev-master ?

**Comment by Jean85** [comment]
I'm preparing the release in #177

**Comment by Jean85** [comment]
https://github.com/getsentry/sentry-symfony/releases/tag/2.2.0

**Comment by bouland** [comment]
Thx,

You ve been so reactive !!

Happy New year
Simon


Le sam. 5 janv. 2019 14:34, Alessandro Lai <notifications@github.com> a
écrit :

**Pull request merged**
