### PR TITLE
Expand configuration

### PR DESCRIPTION
**Pull request by dcramer**
- Add release
- Add environment (default to kernel.environment)
- Add app_path
- Add prefixes

Fixes GH-1

### CODE REVIEW

**Comment by dcramer** [comment]
This will also require a point release of sentry-php

**Comment by Jean85** [comment]
Would love to have this!!
Anything that I can help with to push this further?

**Comment by dcramer** [comment]
@Jean85 thanks for pinging -- forgot about this once we pushed out the updated sentry/sentry release.

**Comment by Jean85** [comment]
Thanks to you @dcramer !
Any plans on tagging this on Packagist?

**Comment by dcramer** [comment]
@Jean85 0.2.0

**Pull request merged**
