### PR TITLE
Use symfony kernel

### PR DESCRIPTION
**Pull request by thomas-medelse**

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
Nice catch, thank you! Can you please fix the build? The code style check is failing.

**Comment by thomas-medelse** [comment]
I don't see the error in my namespace replacement code, can you fix it if you see it?

**Comment by Jean85** [comment]
It's surely due to alphabetical order of the imports. A `make cs` will fix it for you.

**Comment by thomas-medelse** [comment]
The php-cs-fixer does not work on my mac, I tried to correct the error by hand but the test still does not pass.

**Comment by thomas-medelse** [comment]
Thanks

**Pull request merged**
