### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
@Jean85 In this pr - only update Symfony max version code and add allow PHP8

**Comment by Jean85** [comment]
Ok it's confirmed that that's not your fault: https://github.com/getsentry/sentry-symfony/pull/400/checks?check_run_id=1563568113

I'll try to fix the build in #400

**Review by marmichalski — APPROVED** [review]

**Comment by ste93cry** [comment]
@Yozhef can you please try rebasing this PR and see if the CI passes?

**Comment by Yozhef** [comment]
@ste93cry merge master normal or need only rebasing?

**Review by Jean85 — APPROVED** [review]
LGTM! Thanks for the patience!

**Pull request merged**
