### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by Jean85**

### CODE REVIEW

**Comment by ste93cry** [comment]
What's the benefit of this change? I like GitHub Actions even though I didn't use them yet, but I don't see how this could benefit us. Also, much more importantly, does the action you are going to use support Windows? I know we don't test the bundle on it and it doesn't matter so much compared to Linux builds, but it's a thing I would like to do since a long time

**Comment by Jean85** [comment]
I wanted to abandon Travis since the acquisition debacle (https://news.ycombinator.com/item?id=19218036); also their UX is getting less and less responsive.

GA supports Windows, yeah, and it's a lot more fast and responsive, probably due to the tight integration.

**Comment by ste93cry** [comment]
>I wanted to abandon Travis since the acquisition debacle

I would not change a tool that still works great for political reasons, and honestly I see no benefit with this change apart from the fact that it's part of GitHub itself 😉 Said this, I don't intend to block this PR, go ahead if you think it's worth it

**Comment by Jean85** [comment]
Politics aside, it works better and faster: A full run in 1:36 with all checks in parallel: https://github.com/getsentry/sentry-symfony/actions/runs/285923001

**Comment by stayallive** [comment]
@Jean85 I did notice the Zeus webhooks missing...

I would have first checked with @HazAT how important those are for the release cycle since I believe Craft does check in with Zeus. 

If you did check that beforehand don't mind me but otherwise this might have to be reverted.

**Comment by Jean85** [comment]
@stayallive my bad, I forgot about it. Shouldn't be possible to have the same hook from GA too? @HazAT ?

**Comment by HazAT** [comment]
Yes, Zeus also works with GHA

https://github.com/getsentry/sentry-javascript/blob/master/.github/workflows/build.yml#L121

**Comment by stayallive** [comment]
Ah if we don't need Zeus we're good then 👍

**Pull request merged**
