### PR TITLE
Move the static analysis and CS jobs to a separate GitHub Actions workflow

### PR DESCRIPTION
**Pull request by Yozhef**

### CODE REVIEW

**Comment by Yozhef** [comment]
@Jean85 can you review this change? 
And how do you look to add more test on Symfony versions? Сurrently missing on version Symfony 5.

**Comment by Jean85** [comment]
> @Jean85 can you review this change? 
> And how do you look to add more test on Symfony versions? Сurrently missing on version Symfony 5.

Sure, please add a 5.x job

**Comment by Yozhef** [comment]
@Jean85 in this pr https://github.com/getsentry/sentry-symfony/pull/404 - update check in more Symfony version.

**Review by ste93cry — CHANGES_REQUESTED** [review]

**Comment by Yozhef** [comment]
@ste93cry In php-cs has problem hi not support run in php 8.0 - https://github.com/Yozhef/PHP-CS-Fixer/blob/2.17/php-cs-fixer#L26
I'll create a fix for them but I'll leave 7.4 here for now

**Comment by Yozhef** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5394

**Comment by ste93cry** [comment]
>In php-cs has problem hi not support run in php 8.0

It it supported to run the tool on PHP 8 if a certain environment variable is set, what is not supported is running the tool on code written using PHP 8 features. Anyway, it's fine for us to run the tool on PHP 7.4 👍

**Review by ste93cry — APPROVED** [review]

**Pull request merged**
