### PR TITLE
Add handled/unhandled exception support

### PR DESCRIPTION
**Pull request by cs278**
Fixes https://github.com/getsentry/sentry-symfony/issues/670
Requires: https://github.com/getsentry/sentry-php/pull/1430

### CODE REVIEW

**Comment by cs278** [comment]
Need a bit of direction, right now this supports pre 3.11.0 versions of the SDK, I can either:
* Keep that and squash the commits
* Remove the commit and change the Composer requirement

**Comment by cleptric** [comment]
Thanks for the contribution. I can release a new version of `sentry/sdk`, so we can pin it to `3.4`. No need for BC checks.

**Comment by cleptric** [comment]
Cool stuff!
I wonder if we should add a small helper method that encapsulates the boilerplate for 

```
$hint = EventHint::fromArray([
    'exception' => $event->getError(),
    'mechanism' => new ExceptionMechanism(ExceptionMechanism::TYPE_GENERIC, false),
]);

$this->hub->captureEvent(Event::createEvent(), $hint);
```

**Comment by cs278** [comment]
> I wonder if we should add a small helper method that encapsulates the boilerplate for

I looked at this but didn't see anywhere obvious to put such a helper, I figured ideally the `HubInterface` would have a `captureUncaughtException()` method.

**Comment by cleptric** [comment]
Due to our [Unified API](https://develop.sentry.dev/sdk/unified-api/), we can't add functions to the Hub that easily.
Pslam and PHPStan are complaining, we can merge once this is fixed.

**Comment by cs278** [comment]
Update hopefully it passes.

**Comment by cs278** [comment]
@cleptric not sure how I can fix the failing code coverage thing, seems to be missing coverage on parenthesis?

**Comment by cleptric** [comment]
@cs278 No worries, this is fine.

I'll need to test the message stuff, but I'm currently busy with other things.
So please bare with me if this will stay open for a little while.

**Comment by cs278** [comment]
@cleptric polite request for an update. I'm ready to ship changes ditching our custom Sentry 1 Symfony integration and this is the only roadblock left in the way.

**Comment by cleptric** [comment]
I'm still focusing on other SDKs at the moment. Can't really give you a timeline, sorry 😕

**Review by cleptric — APPROVED** [review]
Thanks again for your work on this and sorry for the delay 🙂 
LGTM! 🚢

**Pull request merged**
