### PR TITLE
Allow new excluded_exceptions config

### PR DESCRIPTION
**Pull request by mcfedr**
Adds new config option from https://github.com/getsentry/sentry-php/pull/583

Shouldn't be merged until a new release is made.

I'd really appreciate if this was picked into the 0.8.x branch as well, as I'm currently having to use that version for old php support... its horrible but true...

### CODE REVIEW

**Comment by Jean85** [comment]
Ehi @mcfedr, the Sentry SDK released a 1.9! Can you update your PRs?

**Comment by mcfedr** [comment]
Done, here is a new version with change to `composer.json`

**Comment by Jean85** [comment]
Thanks! Can you also open the same PR targeting the 1.x branch? I would like to backport it there too.

**Comment by mcfedr** [comment]
@Jean85 Maybe its time for a new version of the bundle as this isn't in 2.0.3? Its been quite a while now...

**Comment by Jean85** [comment]
Ouch, I totally forgot about this, thanks for reminding me!
I've added this to the changelog: https://github.com/getsentry/sentry-symfony/pull/159/commits/d39d086f3d4b7a86d7a1d23fef71c549e73a3649

I hope to merge it ASAP.

**Comment by rvanlaak** [comment]
`sentry-symfony` started relying on the SDK's `excluded_exceptions` implementation, which is great but removes that the SDK is aware of Symfony exceptions that did get caught by default before.

We did not have any exceptions configured in `excluded_exceptions` yet, meaning that since `skip_capture` was removed in v3 the defaults the implementation used to rely on are gone.

When upgrade to v3, Sentry starts capturing `HttpExceptionInterface` instances. Did create PR #269 to restore the old behavior.

**Pull request merged**
