### PR TITLE
Update to PHPStan 0.10 and PHPUnit 7

### PR DESCRIPTION
**Pull request by Jean85**

### CODE REVIEW

**Comment by stayallive** [comment]
Why is `/Cannot cast object to string\./` ignored?

**Comment by Jean85** [comment]
Error is reported here: https://github.com/getsentry/sentry-symfony/blob/ee83edf11d36dadf42ab59984c8c69ab94387351/src/EventListener/ExceptionListener.php#L209

PHPStan cannot recognize the `__toString` existence.

**Comment by Jean85** [comment]
PHPStan isn't able to recognize the `method_exists` check here: 

https://github.com/getsentry/sentry-symfony/blob/ee83edf11d36dadf42ab59984c8c69ab94387351/src/EventListener/ExceptionListener.php#L208-L210

See https://github.com/phpstan/phpstan/issues/323#issuecomment-400005174

**Comment by stayallive** [comment]
Cool! I understand :)

**Pull request merged**
