### PR TITLE
Added missing schema option

### PR DESCRIPTION
**Pull request by dragosprotung**

### CODE REVIEW

**Comment by ste93cry** [comment]
Thank you for the contribution, can you please add an entry to the CHANGELOG?

**Comment by dragosprotung** [comment]
Done

**Review by ste93cry — APPROVED** [review]

**Comment by Jean85** [comment]
@ste93cry how did this pass with the tests? Do we miss something there?

**Comment by dragosprotung** [comment]
The integration tests do not validate the XML configuration against the schema.
The field does appear in the tests (see https://github.com/getsentry/sentry-symfony/blob/master/tests/DependencyInjection/Fixtures/xml/full.xml#L29)

**Comment by ste93cry** [comment]
>Do we miss something there?

Yes we do, the `messenger` config node is missing in `tests/DependencyInjection/Fixtures/xml/full.xml` and this caused the tests to not break by fallbacking to the default value for the option

>The integration tests do not validate the XML configuration against the schema.

False, I explained above why the tests didn't break. Try adding the option without your change and Symfony will complain with `[ERROR 1866] Element '{https://sentry.io/schema/dic/sentry-symfony}messenger', attribute 'capture-soft-fails': The attribute 'capture-soft-fails' is not allowed.`. Would you mind opening a new PR to add the missing attribute and fix the tests?

**Comment by dragosprotung** [comment]
Ah, i confused `capture-silenced-errors` with `capture-soft-fails` in the xml fixtures. Opened #420

**Pull request merged**
