### PR TITLE
Replace sentry/sdk by sentry/sentry 3.17

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Same as #693, but updated to 3.17 thanks to https://github.com/getsentry/sentry-php/pull/1504

### CODE REVIEW

**Comment by cleptric** [comment]
Holding off on this for the moment. We don't need to fix what is not broken.
We'll revisit this in the next major of the base SDK.

**Comment by nicolas-grekas** [comment]
The thing that is "broken" is sentry/sdk, which forces a specific client implementation, whereas php-http/discovery already does the job. It's super weird that even the recommended solution is to "replace" the SDK.

Linking to https://github.com/getsentry/sentry-symfony/issues/246 for reference.

**Comment by nicolas-grekas** [comment]
Even the README of this package suggests the "replace". This is something that's solved now, let's clear this up :pray:

**Comment by cleptric** [comment]
> The thing that is "broken" is sentry/sdk, which forces a specific client implementation, whereas php-http/discovery already does the job.

We already ran into many issues due to `php-http/discovery`, and right now, I stand by my decision to postpone any further changes in this regard until the next major version.

This is again in strong alignment with our SDK philosophy: https://develop.sentry.dev/sdk/philosophy/#degrade-gracefully.

I wasn't aware of the mentioned passage in our README, I can take a look if this still applies.

**Comment by nicolas-grekas** [comment]
Let's go for a v2?

**Comment by cleptric** [comment]
v4 of https://github.com/getsentry/sentry-php 😄

**Pull request closed without merging**
