### PR TITLE
Adds ignore_exceptions and ignore_transactions options to Configurator

### PR DESCRIPTION
**Pull request by gassan**
fixes: #710

### CODE REVIEW

**Comment by cleptric** [comment]
In order to move this forward, you'll have to update all tests concerning the newly added options.

**Comment by gassan** [comment]
Has someone fixed an Error while testing on End2EndTest-php:

PHP:  syntax error, unexpected '=' in Unknown on line 24

**Comment by gassan** [comment]
Tests added.

**Review by cleptric — APPROVED** [review]
Thanks!

**Pull request merged**
