### PR TITLE
Give access to all of the RavenClient options

### PR DESCRIPTION
**Pull request by LouisTrezzini**

### CODE REVIEW

**Comment by dcramer** [comment]
Not sure why we never took this approach before. I guess to some degree it makes sense to expose top level options that are very common, but its far too complicated to keep up with all of the options sentry/sentry exposes that way.

Thanks!

**Comment by wachterjohannes** [comment]
@dcramer do you have any approach to release current master with this changes?

**Comment by dcramer** [comment]
@wachterjohannes shipped 0.7.0

**Comment by wachterjohannes** [comment]
thanks for fast response 😁

**Pull request merged**
