### PR TITLE
Dirty workaround for issue #79

### PR DESCRIPTION
**Pull request by hectorj**
I don't think this should be merged as-is, it's just to show a working workaround for issue #79

### CODE REVIEW

**Comment by Jean85** [comment]
Thanks for this PR, is a good starting point!
So, basically you're suggesting re-registering the Symfony error handler after Sentry's. Did you check if Sentry's error reporting still works after this workaround?

**Comment by hectorj** [comment]
Yep. According to my manual testing, I got both the Symfony error page and the error logged by Sentry.

**Comment by hectorj** [comment]
> So, basically you're suggesting re-registering the Symfony error handler after Sentry's.

You also need to `install()` the client only after Symfony's `DebugHandlersListener::configure` ran...

I'm not sure how to get there properly.

**Comment by Jean85** [comment]
I'm investigating on it. I've discovered that:

 * `DebugHandlersListener::configure` is called as an event subscriber on events `kernel.request` and `console.command` with priority 2048; registering on the same events using a lower priority should be enough
 * `ErrorHandler::register` is done at the start of the `FrameworkBundle::boot` function; maybe forcing the bundle to be loaded before it is a feasible solution?

**Comment by hectorj** [comment]
> registering on the same events using a lower priority should be enough

Sadly no. With https://github.com/getsentry/sentry-symfony/blob/008479adca17bbe1a6c29d63f9bfdc470e83f073/src/Resources/config/services.yml#L5-L6, `install()` is called when the listener is instantiated, which is before any events is processed.

That's why in this PR I had to move the `install()` call.

**Comment by Jean85** [comment]
Yes yes, I was referring exactly to that, moving the `install()` inside a listener on those events instead that on instantiation.

That's the easy part, what I'm worried about now is the interaction with Symfony's ErrorHandler, that also converts errors into exceptions, and I think is the root cause of #48

**Comment by hectorj** [comment]
Now that I'm thinking about it, do we really need to do the `install()` ? Symfony already takes care of catching fatal errors, exceptions, etc. with its own ErrorHandler.

I think adding Sentry as a monolog handler would do the job properly, or am I missing something?

**Comment by Jean85** [comment]
Installing the client is done to catch non-halting issues, like notices, warnings and deprecations.

**Comment by hectorj** [comment]
So I was indeed missing something... still, the exception handler doesn't seem to be needed in the context of Symfony.

**Comment by Jean85** [comment]
Why? I want to have all the things reported in Sentry....

**Comment by Jean85** [comment]
I tried the proposed solution in my prod env, still got the blank page, it doesn't seem to work.

Anyhow, as stated previously, the issue resides in the interferences with the Symfony's ErrorHandler... I'm closing this and going back to discuss this in #79

**Pull request closed without merging**
