### PR TITLE
Fix install

### LINKED ISSUE #63: Symfony error pages are not being show correctly
After I enable sentry, when a error 500 happens, the error page is not shown correctly. When I'm in 'dev' environment, the symfony debug page is not shown, as stated in the following images:

Bad:
bad

Good:
good

And when I'm in 'prod' environment, my customized error page is also not shown, as stated in the following images:

Bad:
bad2

Good: 
good2

### PR DESCRIPTION
**Pull request by ragusa87**
Call Raven_Client::install via a listener instead of directly on container boot.
This way, Symfony error handlers are registered before the raven ones, avoiding a few bad behaviors.

Fix #63 #120 

This branch need testing & tagging.

### CODE REVIEW

**Comment by ragusa87** [comment]
@Jean85 Can you take a look to my PR ?
I used another listener to call the Raven_Client install method, and I created a custom configuration to be able to change the listener priorities. I also added two tests.

I made a test project here if needed: https://github.com/ragusa87/sentry-notify, you can adapt the composer.json to use various version of sentry-symfony bundle and see the various behaviors.

**Comment by Jean85** [comment]
Hi @ragusa87, thanks for your work! I'll try to investigate further ASAP, but I fear that lowering the priority for that install will hinder the ability of reporting errors... I'll try to use your app to debug this further.

Were you able to reproduce the issue within your test project, before using this fix?

**Comment by ragusa87** [comment]
Hello @Jean85 , I was able to reproduce the issue with my test project before the fix. Anyway it's currently using my fork so you won't see the problem if you keep the sentry-symfony dependency like this. You have to adapt the composer file to use the official bundle version. 

Removing the install call seems to be a quite better approach. So I think it's better to investigate this solution and close the PR.

**Comment by Jean85** [comment]
Yes, I agree. We can continue discussing this in #63.

**Comment by tmbdrogba** [comment]
+1

**Pull request closed without merging**
