### PR TITLE
Explain PsrLogMessageProcessor

### PR DESCRIPTION
**Pull request by ruudk**
See https://github.com/getsentry/sentry-symfony/pull/293#issuecomment-572525187

### CODE REVIEW

**Comment by ruudk** [comment]
These failures are not related to my work. I guess master is broken.

**Comment by ruudk** [comment]
@guilliamxavier WDYT? Let’s merge it

**Comment by guilliamxavier** [comment]
@ruudk: Maybe
```diff
-It's recommended to enable `PsrLogMessageProcessor`.
+Additionally, you can register the `PsrLogMessageProcessor` to resolve PSR-3 placeholders in reported messages:
```

Anyway I have no right to approve a PR here (but with the suggested change it would look good to me)

**Comment by ruudk** [comment]
@guilliamxavier Would be great to have used the suggest change feature so that I can instantly apply your change.

**Comment by ruudk** [comment]
Feedback applied :)

**Pull request merged**
