### PR TITLE
Fix failing unit tests after Symfony issue #38019 bugfix

### PR DESCRIPTION
**Pull request by ste93cry**
Unit tests for the `TracingRequestListener` class are failing after the release of the fix for symfony/symfony#38019. Since PHP 5.4, the `REQUEST_TIME_FLOAT` element is always present in `$_SERVER`, but Symfony was not setting the value when creating the request object manually, therefore we had to do it ourselves. Now that this is unnecessary, we can cleanup the code

### CODE REVIEW

**Review by Jean85 — CHANGES_REQUESTED** [review]
Ugh. seems we have a fatal on 3.4, where the fix is missing

**Comment by ste93cry** [comment]
Yes I know, the bug is being investigated in symfony/symfony#40390

**Comment by Jean85** [comment]
Issue seems to have been fixed with https://github.com/symfony/symfony/pull/40494, should we wait for a tag?

**Comment by ste93cry** [comment]
Yes, I talked privately with Nicolas and he said me that the new version should be released before the end of the month. The alternative in the meantime would be to fix the `composer.json` to restrict the installed version to a previous version, but I don't think it's worth losing time in doing it by this time

**Comment by Jean85** [comment]
Roger. We need to keep in mind that this same problem is breaking the CI in 3.5.x too, where we have a couple of PR to release as a patch.

**Comment by ste93cry** [comment]
Symfony `5.2.6` has been released and build is now green 🎉

**Review by Jean85 — APPROVED** [review]

**Pull request merged**
