### PR TITLE
Remove space in class_alias

### PR DESCRIPTION
**Pull request by starred-gijs**
Introduced in #309

The space in the classname is obviously a typo.

### CODE REVIEW

**Comment by starred-gijs** [comment]
@Jean85  done.

**Comment by starred-gijs** [comment]
@Jean85 thanks for merging this. What is the strategy/timeframe for releasing a new version?

**Comment by starred-gijs** [comment]
Tag was released. Thanks!

**Comment by rvanlaak** [comment]
https://github.com/getsentry/sentry-symfony/releases/tag/3.4.2 was just released ✔️

**Pull request merged**
