### PR TITLE
Improve the compatibility layer for Doctrine DBAL to avoid side-effects of polyfilling

### PR DESCRIPTION
**Pull request by ste93cry**
This is an attempt at fixing #483 and #484. I decided to split the `TracingDriver` class into two versions, each compatible with just one of the major versions of Doctrine DBAL we support (`2.x` and `3.x`)

### CODE REVIEW

**Comment by ste93cry** [comment]
After thinking again about this, and while we have some clear advantages of splitting the implementation into two, e.g. the fact that we can add typehints to more things and evolve the two classes independently without worrying about keeping the compatibility with both major versions at the same time, I'm pretty sure this does not solve #483 and there is no way to solve it. Basically, the [`DebugClassLoader`](https://github.com/symfony/error-handler/blob/5.3/DebugClassLoader.php) of Symfony blindly parse the annotations on the classes that it loads and as soon as it finds one that is marked as deprecated and that is loaded from something outside of its vendor it reports the deprecation. In our case, we need to implement those deprecated interfaces to expose the fact that the decorated driver implements them, since it's quite common to use an `instanceof` check in this context. I still think that my comment about Symfony not making his own business applies perfectly in this case, the thing that the `DebugClassLoader` is doing would be better suited for a static analysis tool which has far more understanding of the context around how the code is called and how it works

**Review by Jean85 — CHANGES_REQUESTED** [review]
LGTM :+1: splitting is surely a better approach.

Maybe we should declare those implementations `@internal`?

**Comment by ste93cry** [comment]
>Maybe we should declare those implementations `@internal`?

Yes, that's a good idea!

**Review by Jean85 — APPROVED** [review]

**Comment by starred-gijs** [comment]
This PR fixed it already I guess https://github.com/getsentry/sentry-symfony/pull/552

**Comment by Jean85** [comment]
#552 is released as 4.2.3, you can test it out.

**Pull request merged**
